# Generated by Django 4.2 on 2025-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memory_usage', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('ppid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=100)),
                ('cpu_count', models.IntegerField()),
                ('total_memory', models.FloatField()),
                ('available_memory', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
